### ISSUE TITLE
Weirdly high memory usage when calling sleep before or after reading

### ISSUE THREAD

**Issue by efyang** [astro/rust-pulse-simple#2]
As the title says, when continuously reading from a `Record` in a loop, adding a `sleep` causes the memory usage of a program to go up dramatically. For example, in the version without the `sleep`, memory usage stays at a constant 5.3MiB, while in the version with a sleep in the loop, memory usage starts off around the same, but steadily increases at ~0.5MiB/s. The simplified code that gives these same results can be found [here](https://github.com/efyang/pulse-sleep-memory), and the memory usage was measured with `top`. I was hoping that you might be a bit more familiar with the intricacies of the `pa_simple` C api and could give some insights as to what might be causing this? This behavior is consistent across all of the rust `pa_simple` binding libraries.

**Comment by astro** [comment]
In the example you're sleeping for 20ms, reading from Pulseaudio at 50× per second while your receive buffer has capacity for only 256 samples. `50 * 256 = 12800 < 44100`

Memory usage is rising because somewhere some buffering is happening because of this. The following patch fixes the "memory leak" with precisely sufficient capacity for illustration purposes. Make it comfortably large in production code so you can deal with skewed clocks etc.

``` diff
--- src/bin/nosleep.rs
+++ src/bin/nosleep.rs
@@ -4,7 +4,7 @@ use pulse_simple::Record;

 fn main() {
     let p = Record::new("Sleep Test", "Record", None, 44100);
-    let mut buf = [[0f32; 2]; 256];
+    let mut buf = [[0f32; 2]; 882];
     loop {
         ::std::thread::sleep(::std::time::Duration::from_millis(20));
         p.read(&mut buf[..]);
```

Did this solve the issue?

**Comment by efyang** [comment]
It didn't entirely work with 882, but it definitely stopped buffering after I just set it to around 1024. The explanation makes a lot of sense, thanks for the help!
